version: '3.9'

services:
  postgres:
    image: postgres:14.7-alpine
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  redis:
    image: redis
    ports:
      - "6380:6379"
    restart: always

  migrations:
    build: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./backend/core/migrations:/usr/src/app/backend/core/migrations

    command: >
      sh -c "python manage.py migrate --noinput"

  app:


    restart: on-failure
    build: .
    volumes:
      - ./:/usr/src/app
    expose:
      - 8000
    env_file:
      - ./.env.dev
    command:
      sh -c "python ./manage.py makemigrations && python ./manage.py makemigrations main && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    working_dir: /app
    depends_on:
      - postgres
      - migrations

  worker:
    restart: always
    build:
      context: .
    volumes:
      - ./:/app
    command: [ 'celery',  '-A', 'config', 'worker', '-l' ,'INFO' ]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - postgres
      - app
      - redis

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - app
volumes:
  postgres_data:
  static_volume:
  media_volume: