# Generated by Django 4.1.7 on 2023-03-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/home/', max_length=255),
        ),
    ]
